### ISSUE TITLE
Typo in reachset/find.m

### ISSUE THREAD

**Issue by mldiego** [TUMcps/CORA#32]
There is a typo in line 60 of [reachset/find.m,](https://github.com/TUMcps/CORA/blob/master/global/classes/%40reachSet/find.m#L60) it should be:

val = interval(val);

instead of 

val = interal(time);

**Comment by wetzlingerm** [comment]
Thanks a lot for finding this, it has been fixed in the meantime.

**Comment by mldiego** [comment]
I just realized this typo was only partially fixed. The variable in interval should be **val** instead of **time**.
